endpointUrl: ''
email: henrique.martins@mlanalytics.pt
apiKey: whE4IG3gwdbXYRlR3mIX7S3Q1Xsb70kzqMuya5Lt1Go
projects:
  id: 67a53a9e-ccb4-4f57-a2e2-9baafb3f31eb
  parentExperimentId: b0cd7400-5270-4608-bb3e-dc556c5e1cd3